[package]
name = "wav_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.9.2"
console-menu = "0.3.0"
cpal = "0.15.3"
fastapprox = "0.3.1"
image = "0.25.5"
rand = "0.8.5"
plotters = "0.3.7"

[build-dependencies]
slint-build = "1.9.2"
