
// Color palette:
// {"Prussian blue":"273043","Cool gray":"aaadc4","Chamoisee":"8f7e4f","Magenta haze":"a14a76","Carmine":"9b1d20"}
export global Palette {
    out property <color> primary: #273043;
    out property <color> secondary: #8f7e4f;

    out property <color> textcol: #B9E774;

    out property <color> accent1: #aaadc4;
    out property <color> accent2: #a14a76;
    out property <color> accent3: #9b1d20;
}

