import { NumInput } from "./num-input.slint";

export component LabelledInput {
    in property <string> label;
    in property <string> units;

    in property <bool> is_int: true;
    in-out property <float> value <=> inp.value;
    in property <float> min;
    in property <float> max;

    in property <color> text_color;
    in property <color> input_background;

    callback accepted(float);

    HorizontalLayout {
        alignment: center;
        Text {
            text: label + " ";
            color: root.text_color;
        }
        inp := NumInput {
            is_int: root.is_int;
            background: root.input_background;
            text-color: root.text_color;
            min: root.min;
            max: root.max;
            accepted(val) => {
                root.accepted(val);
            }
        }
        Text {
            text: " " + root.units;
            color: root.text_color;
        }
    }
}
